[tool.black]
line-length = 120

[tool.pytest.ini_options]
env = [
  "DOWNLOAD_PATH=tests/download",
  "CONVERTED_PATH=tests/converted",
  "VIDEOS_TEXT_FILE=tests/example.txt"
]
testpaths = [
  "tests",
]

[tool.mypy]
ignore_missing_imports = true
exclude = ["venv/"]